version: '3.8'

# desmembrar o account 
# Vai se chamar youfocus 
# desmembrar o checkout do Selpics
# Horus

services:
  # Aplicação Account
  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    container_name: account-laravel
    ports:
      - "8001:8000"
    volumes:
      - ./account:/var/www/html
      - account-storage:/var/www/html/storage
      - account-vendor:/var/www/html/vendor
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=account-database
      - DB_PORT=3306
      - DB_DATABASE=account_db
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=noreply@account.test
      - MAIL_FROM_NAME="Account App"
    depends_on:
      - account-database
      - account-frontend
      - mailhog
    networks:
      - laravel-network
      - youfocus-network

  # Frontend Account (Vite dev server)
  account-frontend:
    image: node:alpine
    container_name: account-frontend
    volumes:
      - ./account:/var/www/html
    ports:
      - "5179:5179"
    working_dir: /var/www/html
    entrypoint: ["/bin/sh", "-c"]
    command:
      [
        "npm install && chmod -R 755 ./node_modules && npm run dev -- --port 5179 --host 0.0.0.0",
      ]
    networks:
      - laravel-network

  # Banco de dados Account
  account-database:
    image: mysql:8.0
    container_name: account-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=account_db
    ports:
      - "33061:3306"
    volumes:
      - account-database-data:/var/lib/mysql
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOSTS=account-database
      - PMA_PORTS=3306
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
      - UPLOAD_LIMIT=300M
    depends_on:
      - account-database
    networks:
      - laravel-network

  # MailHog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel-network

networks:
  laravel-network:
    external: true
    name: account_laravel-network
  youfocus-network:
    external: true
    name: youfocus_default

volumes:
  account-database-data:
  account-storage:
  account-vendor:
