<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['order' => 1, 'name' => 'Afeganistão', 'alpha2' => 'AF', 'alpha3' => 'AFG', 'numeric_code' => '004'],
            ['order' => 2, 'name' => 'África do Sul', 'alpha2' => 'ZA', 'alpha3' => 'ZAF', 'numeric_code' => '710'],
            ['order' => 3, 'name' => 'Albânia', 'alpha2' => 'AL', 'alpha3' => 'ALB', 'numeric_code' => '008'],
            ['order' => 4, 'name' => 'Alemanha', 'alpha2' => 'DE', 'alpha3' => 'DEU', 'numeric_code' => '276'],
            ['order' => 5, 'name' => 'Andorra', 'alpha2' => 'AD', 'alpha3' => 'AND', 'numeric_code' => '020'],
            ['order' => 6, 'name' => 'Angola', 'alpha2' => 'AO', 'alpha3' => 'AGO', 'numeric_code' => '024'],
            ['order' => 7, 'name' => 'Anguilla', 'alpha2' => 'AI', 'alpha3' => 'AIA', 'numeric_code' => '660'],
            ['order' => 8, 'name' => 'Antártida', 'alpha2' => 'AQ', 'alpha3' => 'ATA', 'numeric_code' => '010'],
            ['order' => 9, 'name' => 'Antígua e Barbuda', 'alpha2' => 'AG', 'alpha3' => 'ATG', 'numeric_code' => '028'],
            ['order' => 10, 'name' => 'Antilhas Holandesas', 'alpha2' => 'AN', 'alpha3' => 'ANT', 'numeric_code' => '530'],
            ['order' => 11, 'name' => 'Arábia Saudita', 'alpha2' => 'SA', 'alpha3' => 'SAU', 'numeric_code' => '682'],
            ['order' => 12, 'name' => 'Argélia', 'alpha2' => 'DZ', 'alpha3' => 'DZA', 'numeric_code' => '012'],
            ['order' => 13, 'name' => 'Argentina', 'alpha2' => 'AR', 'alpha3' => 'ARG', 'numeric_code' => '032'],
            ['order' => 14, 'name' => 'Armênia', 'alpha2' => 'AM', 'alpha3' => 'ARM', 'numeric_code' => '51'],
            ['order' => 15, 'name' => 'Aruba', 'alpha2' => 'AW', 'alpha3' => 'ABW', 'numeric_code' => '533'],
            ['order' => 16, 'name' => 'Austrália', 'alpha2' => 'AU', 'alpha3' => 'AUS', 'numeric_code' => '036'],
            ['order' => 17, 'name' => 'Áustria', 'alpha2' => 'AT', 'alpha3' => 'AUT', 'numeric_code' => '040'],
            ['order' => 18, 'name' => 'Azerbaijão', 'alpha2' => 'AZ', 'alpha3' => 'AZE', 'numeric_code' => '31'],
            ['order' => 19, 'name' => 'Bahamas', 'alpha2' => 'BS', 'alpha3' => 'BHS', 'numeric_code' => '044'],
            ['order' => 20, 'name' => 'Bahrein', 'alpha2' => 'BH', 'alpha3' => 'BHR', 'numeric_code' => '048'],
            ['order' => 21, 'name' => 'Bangladesh', 'alpha2' => 'BD', 'alpha3' => 'BGD', 'numeric_code' => '050'],
            ['order' => 22, 'name' => 'Barbados', 'alpha2' => 'BB', 'alpha3' => 'BRB', 'numeric_code' => '052'],
            ['order' => 23, 'name' => 'Belarus', 'alpha2' => 'BY', 'alpha3' => 'BLR', 'numeric_code' => '112'],
            ['order' => 24, 'name' => 'Bélgica', 'alpha2' => 'BE', 'alpha3' => 'BEL', 'numeric_code' => '056'],
            ['order' => 25, 'name' => 'Belize', 'alpha2' => 'BZ', 'alpha3' => 'BLZ', 'numeric_code' => '084'],
            ['order' => 26, 'name' => 'Benin', 'alpha2' => 'BJ', 'alpha3' => 'BEN', 'numeric_code' => '204'],
            ['order' => 27, 'name' => 'Bermudas', 'alpha2' => 'BM', 'alpha3' => 'BMU', 'numeric_code' => '060'],
            ['order' => 28, 'name' => 'Bolívia', 'alpha2' => 'BO', 'alpha3' => 'BOL', 'numeric_code' => '068'],
            ['order' => 29, 'name' => 'Bósnia-Herzegóvina', 'alpha2' => 'BA', 'alpha3' => 'BIH', 'numeric_code' => '070'],
            ['order' => 30, 'name' => 'Botsuana', 'alpha2' => 'BW', 'alpha3' => 'BWA', 'numeric_code' => '072'],
            ['order' => 31, 'name' => 'Brasil', 'alpha2' => 'BR', 'alpha3' => 'BRA', 'numeric_code' => '076'],
            ['order' => 32, 'name' => 'Brunei', 'alpha2' => 'BN', 'alpha3' => 'BRN', 'numeric_code' => '096'],
            ['order' => 33, 'name' => 'Bulgária', 'alpha2' => 'BG', 'alpha3' => 'BGR', 'numeric_code' => '100'],
            ['order' => 34, 'name' => 'Burkina Fasso', 'alpha2' => 'BF', 'alpha3' => 'BFA', 'numeric_code' => '854'],
            ['order' => 35, 'name' => 'Burundi', 'alpha2' => 'BI', 'alpha3' => 'BDI', 'numeric_code' => '108'],
            ['order' => 36, 'name' => 'Butão', 'alpha2' => 'BT', 'alpha3' => 'BTN', 'numeric_code' => '064'],
            ['order' => 37, 'name' => 'Cabo Verde', 'alpha2' => 'CV', 'alpha3' => 'CPV', 'numeric_code' => '132'],
            ['order' => 38, 'name' => 'Camarões', 'alpha2' => 'CM', 'alpha3' => 'CMR', 'numeric_code' => '120'],
            ['order' => 39, 'name' => 'Camboja', 'alpha2' => 'KH', 'alpha3' => 'KHM', 'numeric_code' => '116'],
            ['order' => 40, 'name' => 'Canadá', 'alpha2' => 'CA', 'alpha3' => 'CAN', 'numeric_code' => '124'],
            ['order' => 41, 'name' => 'Cazaquistão', 'alpha2' => 'KZ', 'alpha3' => 'KAZ', 'numeric_code' => '398'],
            ['order' => 42, 'name' => 'Chade', 'alpha2' => 'TD', 'alpha3' => 'TCD', 'numeric_code' => '148'],
            ['order' => 43, 'name' => 'Chile', 'alpha2' => 'CL', 'alpha3' => 'CHL', 'numeric_code' => '152'],
            ['order' => 44, 'name' => 'China', 'alpha2' => 'CN', 'alpha3' => 'CHN', 'numeric_code' => '156'],
            ['order' => 45, 'name' => 'Chipre', 'alpha2' => 'CY', 'alpha3' => 'CYP', 'numeric_code' => '196'],
            ['order' => 46, 'name' => 'Cingapura', 'alpha2' => 'SG', 'alpha3' => 'SGP', 'numeric_code' => '702'],
            ['order' => 47, 'name' => 'Colômbia', 'alpha2' => 'CO', 'alpha3' => 'COL', 'numeric_code' => '170'],
            ['order' => 48, 'name' => 'Congo', 'alpha2' => 'CG', 'alpha3' => 'COG', 'numeric_code' => '178'],
            ['order' => 49, 'name' => 'Coréia do Norte', 'alpha2' => 'KP', 'alpha3' => 'PRK', 'numeric_code' => '408'],
            ['order' => 50, 'name' => 'Coréia do Sul', 'alpha2' => 'KR', 'alpha3' => 'KOR', 'numeric_code' => '410'],
            ['order' => 51, 'name' => 'Costa do Marfim', 'alpha2' => 'CI', 'alpha3' => 'CIV', 'numeric_code' => '384'],
            ['order' => 52, 'name' => 'Costa Rica', 'alpha2' => 'CR', 'alpha3' => 'CRI', 'numeric_code' => '188'],
            ['order' => 53, 'name' => 'Croácia (Hrvatska)', 'alpha2' => 'HR', 'alpha3' => 'HRV', 'numeric_code' => '191'],
            ['order' => 54, 'name' => 'Cuba', 'alpha2' => 'CU', 'alpha3' => 'CUB', 'numeric_code' => '192'],
            ['order' => 55, 'name' => 'Dinamarca', 'alpha2' => 'DK', 'alpha3' => 'DNK', 'numeric_code' => '208'],
            ['order' => 56, 'name' => 'Djibuti', 'alpha2' => 'DJ', 'alpha3' => 'DJI', 'numeric_code' => '262'],
            ['order' => 57, 'name' => 'Dominica', 'alpha2' => 'DM', 'alpha3' => 'DMA', 'numeric_code' => '212'],
            ['order' => 58, 'name' => 'Egito', 'alpha2' => 'EG', 'alpha3' => 'EGY', 'numeric_code' => '818'],
            ['order' => 59, 'name' => 'El Salvador', 'alpha2' => 'SV', 'alpha3' => 'SLV', 'numeric_code' => '222'],
            ['order' => 60, 'name' => 'Emirados Árabes Unidos', 'alpha2' => 'AE', 'alpha3' => 'ARE', 'numeric_code' => '784'],
            ['order' => 61, 'name' => 'Equador', 'alpha2' => 'EC', 'alpha3' => 'ECU', 'numeric_code' => '218'],
            ['order' => 62, 'name' => 'Eritréia', 'alpha2' => 'ER', 'alpha3' => 'ERI', 'numeric_code' => '232'],
            ['order' => 63, 'name' => 'Eslováquia', 'alpha2' => 'SK', 'alpha3' => 'SVK', 'numeric_code' => '703'],
            ['order' => 64, 'name' => 'Eslovênia', 'alpha2' => 'SI', 'alpha3' => 'SVN', 'numeric_code' => '705'],
            ['order' => 65, 'name' => 'Espanha', 'alpha2' => 'ES', 'alpha3' => 'ESP', 'numeric_code' => '724'],
            ['order' => 66, 'name' => 'Estados Unidos', 'alpha2' => 'US', 'alpha3' => 'USA', 'numeric_code' => '840'],
            ['order' => 67, 'name' => 'Estônia', 'alpha2' => 'EE', 'alpha3' => 'EST', 'numeric_code' => '233'],
            ['order' => 68, 'name' => 'Etiópia', 'alpha2' => 'ET', 'alpha3' => 'ETH', 'numeric_code' => '231'],
            ['order' => 69, 'name' => 'Fiji', 'alpha2' => 'FJ', 'alpha3' => 'FJI', 'numeric_code' => '242'],
            ['order' => 70, 'name' => 'Filipinas', 'alpha2' => 'PH', 'alpha3' => 'PHL', 'numeric_code' => '608'],
            ['order' => 71, 'name' => 'Finlândia', 'alpha2' => 'FI', 'alpha3' => 'FIN', 'numeric_code' => '246'],
            ['order' => 72, 'name' => 'França', 'alpha2' => 'FR', 'alpha3' => 'FRA', 'numeric_code' => '250'],
            ['order' => 73, 'name' => 'Gabão', 'alpha2' => 'GA', 'alpha3' => 'GAB', 'numeric_code' => '266'],
            ['order' => 74, 'name' => 'Gâmbia', 'alpha2' => 'GM', 'alpha3' => 'GMB', 'numeric_code' => '270'],
            ['order' => 75, 'name' => 'Gana', 'alpha2' => 'GH', 'alpha3' => 'GHA', 'numeric_code' => '288'],
            ['order' => 76, 'name' => 'Geórgia', 'alpha2' => 'GE', 'alpha3' => 'GEO', 'numeric_code' => '268'],
            ['order' => 77, 'name' => 'Gibraltar', 'alpha2' => 'GI', 'alpha3' => 'GIB', 'numeric_code' => '292'],
            ['order' => 78, 'name' => 'Grã-Bretanha (Reino Unido, UK)', 'alpha2' => 'GB', 'alpha3' => 'GBR', 'numeric_code' => '826'],
            ['order' => 79, 'name' => 'Granada', 'alpha2' => 'GD', 'alpha3' => 'GRD', 'numeric_code' => '308'],
            ['order' => 80, 'name' => 'Grécia', 'alpha2' => 'GR', 'alpha3' => 'GRC', 'numeric_code' => '300'],
            ['order' => 81, 'name' => 'Groelândia', 'alpha2' => 'GL', 'alpha3' => 'GRL', 'numeric_code' => '304'],
            ['order' => 82, 'name' => 'Guadalupe', 'alpha2' => 'GP', 'alpha3' => 'GLP', 'numeric_code' => '312'],
            ['order' => 83, 'name' => 'Guam (Território dos Estados Unidos)', 'alpha2' => 'GU', 'alpha3' => 'GUM', 'numeric_code' => '316'],
            ['order' => 84, 'name' => 'Guatemala', 'alpha2' => 'GT', 'alpha3' => 'GTM', 'numeric_code' => '320'],
            // ['order' => 85, 'name' => 'Guernsey', 'alpha2' => 'GG', 'alpha3' => 'GGY', 'numeric_code' => '832'],
            ['order' => 86, 'name' => 'Guiana', 'alpha2' => 'GY', 'alpha3' => 'GUY', 'numeric_code' => '328'],
            ['order' => 87, 'name' => 'Guiana Francesa', 'alpha2' => 'GF', 'alpha3' => 'GUF', 'numeric_code' => '254'],
            ['order' => 88, 'name' => 'Guiné', 'alpha2' => 'GN', 'alpha3' => 'GIN', 'numeric_code' => '324'],
            ['order' => 89, 'name' => 'Guiné Equatorial', 'alpha2' => 'GQ', 'alpha3' => 'GNQ', 'numeric_code' => '226'],
            ['order' => 90, 'name' => 'Guiné-Bissau', 'alpha2' => 'GW', 'alpha3' => 'GNB', 'numeric_code' => '624'],
            ['order' => 91, 'name' => 'Haiti', 'alpha2' => 'HT', 'alpha3' => 'HTI', 'numeric_code' => '332'],
            ['order' => 93, 'name' => 'Honduras', 'alpha2' => 'HN', 'alpha3' => 'HND', 'numeric_code' => '340'],
            ['order' => 94, 'name' => 'Hong Kong', 'alpha2' => 'HK', 'alpha3' => 'HKG', 'numeric_code' => '344'],
            ['order' => 95, 'name' => 'Hungria', 'alpha2' => 'HU', 'alpha3' => 'HUN', 'numeric_code' => '348'],
            ['order' => 96, 'name' => 'Iêmen', 'alpha2' => 'YE', 'alpha3' => 'YEM', 'numeric_code' => '887'],
            ['order' => 97, 'name' => 'Ilha Bouvet (Território da Noruega)', 'alpha2' => 'BV', 'alpha3' => 'BVT', 'numeric_code' => '074'],
            ['order' => 98, 'name' => 'Ilha do Homem', 'alpha2' => 'IM', 'alpha3' => 'IMN', 'numeric_code' => '833'],
            ['order' => 99, 'name' => 'Ilha Natal', 'alpha2' => 'CX', 'alpha3' => 'CXR', 'numeric_code' => '162'],
            ['order' => 100, 'name' => 'Ilha Pitcairn', 'alpha2' => 'PN', 'alpha3' => 'PCN', 'numeric_code' => '612'],
            ['order' => 101, 'name' => 'Ilha Reunião', 'alpha2' => 'RE', 'alpha3' => 'REU', 'numeric_code' => '638'],
            ['order' => 102, 'name' => 'Ilhas Aland', 'alpha2' => 'AX', 'alpha3' => 'ALA', 'numeric_code' => '248'],
            ['order' => 103, 'name' => 'Ilhas Cayman', 'alpha2' => 'KY', 'alpha3' => 'CYM', 'numeric_code' => '136'],
            ['order' => 104, 'name' => 'Ilhas Cocos', 'alpha2' => 'CC', 'alpha3' => 'CCK', 'numeric_code' => '166'],
            ['order' => 105, 'name' => 'Ilhas Comores', 'alpha2' => 'KM', 'alpha3' => 'COM', 'numeric_code' => '174'],
            ['order' => 106, 'name' => 'Ilhas Cook', 'alpha2' => 'CK', 'alpha3' => 'COK', 'numeric_code' => '184'],
            ['order' => 107, 'name' => 'Ilhas Faroes', 'alpha2' => 'FO', 'alpha3' => 'FRO', 'numeric_code' => '234'],
            ['order' => 108, 'name' => 'Ilhas Falkland (Malvinas)', 'alpha2' => 'FK', 'alpha3' => 'FLK', 'numeric_code' => '238'],
            ['order' => 109, 'name' => 'Ilhas Geórgia do Sul e Sandwich do Sul', 'alpha2' => 'GS', 'alpha3' => 'SGS', 'numeric_code' => '239'],
            ['order' => 110, 'name' => 'Ilhas Heard e McDonald (Território da Austrália)', 'alpha2' => 'HM', 'alpha3' => 'HMD', 'numeric_code' => '334'],
            ['order' => 111, 'name' => 'Ilhas Marianas do Norte', 'alpha2' => 'MP', 'alpha3' => 'MNP', 'numeric_code' => '580'],
            ['order' => 112, 'name' => 'Ilhas Marshall', 'alpha2' => 'MH', 'alpha3' => 'MHL', 'numeric_code' => '584'],
            ['order' => 114, 'name' => 'Ilhas Norfolk', 'alpha2' => 'NF', 'alpha3' => 'NFK', 'numeric_code' => '574'],
            ['order' => 115, 'name' => 'Ilhas Seychelles', 'alpha2' => 'SC', 'alpha3' => 'SYC', 'numeric_code' => '690'],
            ['order' => 116, 'name' => 'Ilhas Solomão', 'alpha2' => 'SB', 'alpha3' => 'SLB', 'numeric_code' => '090'],
            ['order' => 117, 'name' => 'Ilhas Svalbard e Jan Mayen', 'alpha2' => 'SJ', 'alpha3' => 'SJM', 'numeric_code' => '744'],
            ['order' => 118, 'name' => 'Ilhas Tokelau', 'alpha2' => 'TK', 'alpha3' => 'TKL', 'numeric_code' => '772'],
            ['order' => 119, 'name' => 'Ilhas Turks e Caicos', 'alpha2' => 'TC', 'alpha3' => 'TCA', 'numeric_code' => '796'],
            ['order' => 120, 'name' => 'Ilhas Virgens (Estados Unidos)', 'alpha2' => 'VI', 'alpha3' => 'VIR', 'numeric_code' => '850'],
            ['order' => 121, 'name' => 'Ilhas Virgens (Inglaterra)', 'alpha2' => 'VG', 'alpha3' => 'VGB', 'numeric_code' => '092'],
            ['order' => 122, 'name' => 'Ilhas Wallis e Futuna', 'alpha2' => 'WF', 'alpha3' => 'WLF', 'numeric_code' => '876'],
            ['order' => 123, 'name' => 'índia', 'alpha2' => 'IN', 'alpha3' => 'IND', 'numeric_code' => '356'],
            ['order' => 124, 'name' => 'Indonésia', 'alpha2' => 'ID', 'alpha3' => 'IDN', 'numeric_code' => '360'],
            ['order' => 125, 'name' => 'Irã', 'alpha2' => 'IR', 'alpha3' => 'IRN', 'numeric_code' => '364'],
            ['order' => 126, 'name' => 'Iraque', 'alpha2' => 'IQ', 'alpha3' => 'IRQ', 'numeric_code' => '368'],
            ['order' => 127, 'name' => 'Irlanda', 'alpha2' => 'IE', 'alpha3' => 'IRL', 'numeric_code' => '372'],
            ['order' => 128, 'name' => 'Islândia', 'alpha2' => 'IS', 'alpha3' => 'ISL', 'numeric_code' => '352'],
            ['order' => 129, 'name' => 'Israel', 'alpha2' => 'IL', 'alpha3' => 'ISR', 'numeric_code' => '376'],
            ['order' => 130, 'name' => 'Itália', 'alpha2' => 'IT', 'alpha3' => 'ITA', 'numeric_code' => '380'],
            ['order' => 131, 'name' => 'Jamaica', 'alpha2' => 'JM', 'alpha3' => 'JAM', 'numeric_code' => '388'],
            ['order' => 132, 'name' => 'Japão', 'alpha2' => 'JP', 'alpha3' => 'JPN', 'numeric_code' => '392'],
            ['order' => 133, 'name' => 'Jersey', 'alpha2' => 'JE', 'alpha3' => 'JEY', 'numeric_code' => '832'],
            ['order' => 134, 'name' => 'Jordânia', 'alpha2' => 'JO', 'alpha3' => 'JOR', 'numeric_code' => '400'],
            ['order' => 135, 'name' => 'Kênia', 'alpha2' => 'KE', 'alpha3' => 'KEN', 'numeric_code' => '404'],
            ['order' => 136, 'name' => 'Kiribati', 'alpha2' => 'KI', 'alpha3' => 'KIR', 'numeric_code' => '296'],
            ['order' => 137, 'name' => 'Kuait', 'alpha2' => 'KW', 'alpha3' => 'KWT', 'numeric_code' => '414'],
            ['order' => 138, 'name' => 'Laos', 'alpha2' => 'LA', 'alpha3' => 'LAO', 'numeric_code' => '418'],
            ['order' => 139, 'name' => 'Látvia', 'alpha2' => 'LV', 'alpha3' => 'LVA', 'numeric_code' => '428'],
            ['order' => 140, 'name' => 'Lesoto', 'alpha2' => 'LS', 'alpha3' => 'LSO', 'numeric_code' => '426'],
            ['order' => 141, 'name' => 'Líbano', 'alpha2' => 'LB', 'alpha3' => 'LBN', 'numeric_code' => '422'],
            ['order' => 142, 'name' => 'Libéria', 'alpha2' => 'LR', 'alpha3' => 'LBR', 'numeric_code' => '430'],
            ['order' => 143, 'name' => 'Líbia', 'alpha2' => 'LY', 'alpha3' => 'LBY', 'numeric_code' => '434'],
            ['order' => 144, 'name' => 'Liechtenstein', 'alpha2' => 'LI', 'alpha3' => 'LIE', 'numeric_code' => '438'],
            ['order' => 145, 'name' => 'Lituânia', 'alpha2' => 'LT', 'alpha3' => 'LTU', 'numeric_code' => '440'],
            ['order' => 146, 'name' => 'Luxemburgo', 'alpha2' => 'LU', 'alpha3' => 'LUX', 'numeric_code' => '442'],
            ['order' => 147, 'name' => 'Macau', 'alpha2' => 'MO', 'alpha3' => 'MAC', 'numeric_code' => '446'],
            ['order' => 148, 'name' => 'Macedônia (República Yugoslava)', 'alpha2' => 'MK', 'alpha3' => 'MKD', 'numeric_code' => '807'],
            ['order' => 149, 'name' => 'Madagascar', 'alpha2' => 'MG', 'alpha3' => 'MDG', 'numeric_code' => '450'],
            ['order' => 150, 'name' => 'Malásia', 'alpha2' => 'MY', 'alpha3' => 'MYS', 'numeric_code' => '458'],
            ['order' => 151, 'name' => 'Malaui', 'alpha2' => 'MW', 'alpha3' => 'MWI', 'numeric_code' => '454'],
            ['order' => 152, 'name' => 'Maldivas', 'alpha2' => 'MV', 'alpha3' => 'MDV', 'numeric_code' => '462'],
            ['order' => 153, 'name' => 'Mali', 'alpha2' => 'ML', 'alpha3' => 'MLI', 'numeric_code' => '466'],
            ['order' => 154, 'name' => 'Malta', 'alpha2' => 'MT', 'alpha3' => 'MLT', 'numeric_code' => '470'],
            ['order' => 155, 'name' => 'Marrocos', 'alpha2' => 'MA', 'alpha3' => 'MAR', 'numeric_code' => '504'],
            ['order' => 156, 'name' => 'Martinica', 'alpha2' => 'MQ', 'alpha3' => 'MTQ', 'numeric_code' => '474'],
            ['order' => 157, 'name' => 'Maurício', 'alpha2' => 'MU', 'alpha3' => 'MUS', 'numeric_code' => '480'],
            ['order' => 158, 'name' => 'Mauritânia', 'alpha2' => 'MR', 'alpha3' => 'MRT', 'numeric_code' => '478'],
            ['order' => 159, 'name' => 'Mayotte', 'alpha2' => 'YT', 'alpha3' => 'MYT', 'numeric_code' => '175'],
            ['order' => 160, 'name' => 'México', 'alpha2' => 'MX', 'alpha3' => 'MEX', 'numeric_code' => '484'],
            ['order' => 161, 'name' => 'Micronésia', 'alpha2' => 'FM', 'alpha3' => 'FSM', 'numeric_code' => '583'],
            ['order' => 162, 'name' => 'Moçambique', 'alpha2' => 'MZ', 'alpha3' => 'MOZ', 'numeric_code' => '508'],
            ['order' => 163, 'name' => 'Moldova', 'alpha2' => 'MD', 'alpha3' => 'MDA', 'numeric_code' => '498'],
            ['order' => 164, 'name' => 'Mônaco', 'alpha2' => 'MC', 'alpha3' => 'MCO', 'numeric_code' => '492'],
            ['order' => 165, 'name' => 'Mongólia', 'alpha2' => 'MN', 'alpha3' => 'MNG', 'numeric_code' => '496'],
            ['order' => 166, 'name' => 'Montenegro', 'alpha2' => 'ME', 'alpha3' => 'MNE', 'numeric_code' => '499'],
            ['order' => 167, 'name' => 'Montserrat', 'alpha2' => 'MS', 'alpha3' => 'MSR', 'numeric_code' => '500'],
            ['order' => 168, 'name' => 'Myanma', 'alpha2' => 'MM', 'alpha3' => 'MMR', 'numeric_code' => '104'],
            ['order' => 169, 'name' => 'Namíbia', 'alpha2' => 'NA', 'alpha3' => 'NAM', 'numeric_code' => '516'],
            ['order' => 170, 'name' => 'Nauru', 'alpha2' => 'NR', 'alpha3' => 'NRU', 'numeric_code' => '520'],
            ['order' => 171, 'name' => 'Nepal', 'alpha2' => 'NP', 'alpha3' => 'NPL', 'numeric_code' => '524'],
            ['order' => 172, 'name' => 'Nicarágua', 'alpha2' => 'NI', 'alpha3' => 'NIC', 'numeric_code' => '558'],
            ['order' => 173, 'name' => 'Níger', 'alpha2' => 'NE', 'alpha3' => 'NER', 'numeric_code' => '562'],
            ['order' => 174, 'name' => 'Nigéria', 'alpha2' => 'NG', 'alpha3' => 'NGA', 'numeric_code' => '566'],
            ['order' => 175, 'name' => 'Niue', 'alpha2' => 'NU', 'alpha3' => 'NIU', 'numeric_code' => '570'],
            ['order' => 176, 'name' => 'Noruega', 'alpha2' => 'NO', 'alpha3' => 'NOR', 'numeric_code' => '578'],
            ['order' => 177, 'name' => 'Nova Caledônia', 'alpha2' => 'NC', 'alpha3' => 'NCL', 'numeric_code' => '540'],
            ['order' => 178, 'name' => 'Nova Zelândia', 'alpha2' => 'NZ', 'alpha3' => 'NZL', 'numeric_code' => '554'],
            ['order' => 179, 'name' => 'Omã', 'alpha2' => 'OM', 'alpha3' => 'OMN', 'numeric_code' => '512'],
            ['order' => 180, 'name' => 'Palau', 'alpha2' => 'PW', 'alpha3' => 'PLW', 'numeric_code' => '585'],
            ['order' => 181, 'name' => 'Panamá', 'alpha2' => 'PA', 'alpha3' => 'PAN', 'numeric_code' => '591'],
            ['order' => 182, 'name' => 'Papua-Nova Guiné', 'alpha2' => 'PG', 'alpha3' => 'PNG', 'numeric_code' => '598'],
            ['order' => 183, 'name' => 'Paquistão', 'alpha2' => 'PK', 'alpha3' => 'PAK', 'numeric_code' => '586'],
            ['order' => 184, 'name' => 'Paraguai', 'alpha2' => 'PY', 'alpha3' => 'PRY', 'numeric_code' => '600'],
            ['order' => 185, 'name' => 'Peru', 'alpha2' => 'PE', 'alpha3' => 'PER', 'numeric_code' => '604'],
            ['order' => 186, 'name' => 'Polinésia Francesa', 'alpha2' => 'PF', 'alpha3' => 'PYF', 'numeric_code' => '258'],
            ['order' => 187, 'name' => 'Polônia', 'alpha2' => 'PL', 'alpha3' => 'POL', 'numeric_code' => '616'],
            ['order' => 188, 'name' => 'Porto Rico', 'alpha2' => 'PR', 'alpha3' => 'PRI', 'numeric_code' => '630'],
            ['order' => 189, 'name' => 'Portugal', 'alpha2' => 'PT', 'alpha3' => 'PRT', 'numeric_code' => '620'],
            ['order' => 190, 'name' => 'Qatar', 'alpha2' => 'QA', 'alpha3' => 'QAT', 'numeric_code' => '634'],
            ['order' => 191, 'name' => 'Quirguistão', 'alpha2' => 'KG', 'alpha3' => 'KGZ', 'numeric_code' => '417'],
            ['order' => 192, 'name' => 'República Centro-Africana', 'alpha2' => 'CF', 'alpha3' => 'CAF', 'numeric_code' => '140'],
            ['order' => 193, 'name' => 'República Democrática do Congo', 'alpha2' => 'CD', 'alpha3' => 'COD', 'numeric_code' => '180'],
            ['order' => 194, 'name' => 'República Dominicana', 'alpha2' => 'DO', 'alpha3' => 'DOM', 'numeric_code' => '214'],
            ['order' => 195, 'name' => 'República Tcheca', 'alpha2' => 'CZ', 'alpha3' => 'CZE', 'numeric_code' => '203'],
            ['order' => 196, 'name' => 'Romênia', 'alpha2' => 'RO', 'alpha3' => 'ROM', 'numeric_code' => '642'],
            ['order' => 197, 'name' => 'Ruanda', 'alpha2' => 'RW', 'alpha3' => 'RWA', 'numeric_code' => '646'],
            ['order' => 198, 'name' => 'Rússia (antiga URSS) - Federação Russa', 'alpha2' => 'RU', 'alpha3' => 'RUS', 'numeric_code' => '643'],
            ['order' => 199, 'name' => 'Saara Ocidental', 'alpha2' => 'EH', 'alpha3' => 'ESH', 'numeric_code' => '732'],
            ['order' => 200, 'name' => 'Saint Vincente e Granadinas', 'alpha2' => 'VC', 'alpha3' => 'VCT', 'numeric_code' => '670'],
            ['order' => 201, 'name' => 'Samoa Americana', 'alpha2' => 'AS', 'alpha3' => 'ASM', 'numeric_code' => '016'],
            ['order' => 202, 'name' => 'Samoa Ocidental', 'alpha2' => 'WS', 'alpha3' => 'WSM', 'numeric_code' => '882'],
            ['order' => 203, 'name' => 'San Marino', 'alpha2' => 'SM', 'alpha3' => 'SMR', 'numeric_code' => '674'],
            ['order' => 204, 'name' => 'Santa Helena', 'alpha2' => 'SH', 'alpha3' => 'SHN', 'numeric_code' => '654'],
            ['order' => 205, 'name' => 'Santa Lúcia', 'alpha2' => 'LC', 'alpha3' => 'LCA', 'numeric_code' => '662'],
            ['order' => 206, 'name' => 'São Bartolomeu', 'alpha2' => 'BL', 'alpha3' => 'BLM', 'numeric_code' => '652'],
            ['order' => 207, 'name' => 'São Cristóvão e Névis', 'alpha2' => 'KN', 'alpha3' => 'KNA', 'numeric_code' => '659'],
            ['order' => 208, 'name' => 'São Martim', 'alpha2' => 'MF', 'alpha3' => 'MAF', 'numeric_code' => '663'],
            ['order' => 209, 'name' => 'São Tomé e Príncipe', 'alpha2' => 'ST', 'alpha3' => 'STP', 'numeric_code' => '678'],
            ['order' => 210, 'name' => 'Senegal', 'alpha2' => 'SN', 'alpha3' => 'SEN', 'numeric_code' => '686'],
            ['order' => 211, 'name' => 'Serra Leoa', 'alpha2' => 'SL', 'alpha3' => 'SLE', 'numeric_code' => '694'],
            ['order' => 212, 'name' => 'Sérvia', 'alpha2' => 'RS', 'alpha3' => 'SRB', 'numeric_code' => '688'],
            ['order' => 213, 'name' => 'Síria', 'alpha2' => 'SY', 'alpha3' => 'SYR', 'numeric_code' => '760'],
            ['order' => 214, 'name' => 'Somália', 'alpha2' => 'SO', 'alpha3' => 'SOM', 'numeric_code' => '706'],
            ['order' => 215, 'name' => 'Sri Lanka', 'alpha2' => 'LK', 'alpha3' => 'LKA', 'numeric_code' => '144'],
            ['order' => 216, 'name' => 'St. Pierre and Miquelon', 'alpha2' => 'PM', 'alpha3' => 'SPM', 'numeric_code' => '666'],
            ['order' => 217, 'name' => 'Suazilândia', 'alpha2' => 'SZ', 'alpha3' => 'SWZ', 'numeric_code' => '748'],
            ['order' => 218, 'name' => 'Sudão', 'alpha2' => 'SD', 'alpha3' => 'SDN', 'numeric_code' => '736'],
            ['order' => 219, 'name' => 'Suécia', 'alpha2' => 'SE', 'alpha3' => 'SWE', 'numeric_code' => '752'],
            ['order' => 220, 'name' => 'Suíça', 'alpha2' => 'CH', 'alpha3' => 'CHE', 'numeric_code' => '756'],
            ['order' => 221, 'name' => 'Suriname', 'alpha2' => 'SR', 'alpha3' => 'SUR', 'numeric_code' => '740'],
            ['order' => 222, 'name' => 'Tadjiquistão', 'alpha2' => 'TJ', 'alpha3' => 'TJK', 'numeric_code' => '762'],
            ['order' => 223, 'name' => 'Tailândia', 'alpha2' => 'TH', 'alpha3' => 'THA', 'numeric_code' => '764'],
            ['order' => 225, 'name' => 'Tanzânia', 'alpha2' => 'TZ', 'alpha3' => 'TZA', 'numeric_code' => '834'],
            ['order' => 226, 'name' => 'Território Britânico do Oceano índico', 'alpha2' => 'IO', 'alpha3' => 'IOT', 'numeric_code' => '086'],
            ['order' => 227, 'name' => 'Territórios do Sul da França', 'alpha2' => 'TF', 'alpha3' => 'ATF', 'numeric_code' => '260'],
            ['order' => 228, 'name' => 'Territórios Palestinos Ocupados', 'alpha2' => 'PS', 'alpha3' => 'PSE', 'numeric_code' => '275'],
            ['order' => 230, 'name' => 'Togo', 'alpha2' => 'TG', 'alpha3' => 'TGO', 'numeric_code' => '768'],
            ['order' => 231, 'name' => 'Tonga', 'alpha2' => 'TO', 'alpha3' => 'TON', 'numeric_code' => '776'],
            ['order' => 232, 'name' => 'Trinidad and Tobago', 'alpha2' => 'TT', 'alpha3' => 'TTO', 'numeric_code' => '780'],
            ['order' => 233, 'name' => 'Tunísia', 'alpha2' => 'TN', 'alpha3' => 'TUN', 'numeric_code' => '788'],
            ['order' => 234, 'name' => 'Turcomenistão', 'alpha2' => 'TM', 'alpha3' => 'TKM', 'numeric_code' => '795'],
            ['order' => 235, 'name' => 'Turquia', 'alpha2' => 'TR', 'alpha3' => 'TUR', 'numeric_code' => '792'],
            ['order' => 236, 'name' => 'Tuvalu', 'alpha2' => 'TV', 'alpha3' => 'TUV', 'numeric_code' => '798'],
            ['order' => 237, 'name' => 'Ucrânia', 'alpha2' => 'UA', 'alpha3' => 'UKR', 'numeric_code' => '804'],
            ['order' => 238, 'name' => 'Uganda', 'alpha2' => 'UG', 'alpha3' => 'UGA', 'numeric_code' => '800'],
            ['order' => 239, 'name' => 'Uruguai', 'alpha2' => 'UY', 'alpha3' => 'URY', 'numeric_code' => '858'],
            ['order' => 240, 'name' => 'Uzbequistão', 'alpha2' => 'UZ', 'alpha3' => 'UZB', 'numeric_code' => '860'],
            ['order' => 241, 'name' => 'Vanuatu', 'alpha2' => 'VU', 'alpha3' => 'VUT', 'numeric_code' => '548'],
            ['order' => 242, 'name' => 'Vaticano', 'alpha2' => 'VA', 'alpha3' => 'VAT', 'numeric_code' => '336'],
            ['order' => 243, 'name' => 'Venezuela', 'alpha2' => 'VE', 'alpha3' => 'VEN', 'numeric_code' => '862'],
            ['order' => 244, 'name' => 'Vietnã', 'alpha2' => 'VN', 'alpha3' => 'VNM', 'numeric_code' => '704'],
            ['order' => 245, 'name' => 'Zâmbia', 'alpha2' => 'ZM', 'alpha3' => 'ZMB', 'numeric_code' => '894'],
            ['order' => 246, 'name' => 'Zimbábue', 'alpha2' => 'ZW', 'alpha3' => 'ZWE', 'numeric_code' => '716'],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['alpha2' => $country['alpha2']],
                [
                    'order' => $country['order'],
                    'name' => $country['name'],
                    'alpha2' => $country['alpha2'],
                    'alpha3' => $country['alpha3'],
                    'numeric_code' => $country['numeric_code'],
                    'flag' => "static/common/flags/{$country['alpha2']}.png",
                ]
            );
        }
    }
}
